[
    {
        "major_versions": [
            4
        ],
        "req": {
            "cmd": "invite_greeter_cancel_attempt",
            "fields": [
                {
                    "name": "token",
                    "type": "InvitationToken"
                },
                {
                    "name": "attempt",
                    "type": "AttemptID"
                },
                {
                    "name": "reason",
                    // TODO: define dedicated type
                    "type": "Integer"
                }
            ]
        },
        "reps": [
            {
                "status": "ok",
                "fields": [
                    {
                        "name": "attempt",
                        "type": "AttemptID"
                    }
                ]
            },
            {
                // The invitation token doesn't correspond to any existing invitation
                "status": "invitation_not_found"
            },
            {
                // The invitation has already been completed
                "status": "invitation_completed"
            },
            {
                // The invitation has been cancelled
                "status": "invitation_cancelled"
            },
            {
                // The author is not part of the allowed greeters for this invitation
                "status": "author_not_allowed"
            },
            {
                // The attempt id doesn't correspond to any existing attempt
                "status": "attempt_not_found"
            },
            {
                // The author did not join the attempt
                // This should not happen, since joining is required to get the attempt ID
                "status": "attempt_not_joined"
            },
            {
                // The attempt has been already cancelled
                "status": "attempt_already_cancelled"
            }
        ]
    }
]
